# Generated by Django 5.0.7 on 2024-08-01 09:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profil', models.ImageField(default='uploads/Manager_/unknown_pdp.png', upload_to='uploads/Manager_')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('profil', models.ImageField(default='uploads/Membre/unknown_pdp.jpg', upload_to='uploads/Membre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('file', models.FileField(null=True, upload_to='')),
                ('membres', models.ManyToManyField(to='gestion_projet.membre')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('anomalie', 'Anomalie'), ('parametrage', 'Paramétrage Système'), ('info', "Demande d'Information")], max_length=20)),
                ('etat', models.CharField(choices=[('declare', 'Déclaré'), ('analyse', "En cours d'analyse"), ('traitement', 'En cours de traitement'), ('rejete', 'Rejeté'), ('cloture', 'Cloturé')], default=('declare', 'Déclaré'), max_length=20)),
                ('Intitulé', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_projet.projet')),
            ],
        ),
    ]
