# Generated by Django 5.0.7 on 2024-08-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.CharField(choices=[('declare', 'Déclaré'), ('analyse', "En cours d'analyse"), ('traitement', 'En cours de traitement'), ('rejete', 'Rejeté'), ('cloture', 'Cloturé')], default='declare', max_length=20),
        ),
    ]
