# Generated by Django 5.0.7 on 2024-08-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0002_alter_ticket_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_creation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='membre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion_projet.membre'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='moment_creation',
            field=models.TimeField(null=True),
        ),
    ]
