# Generated by Django 5.0.7 on 2024-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0006_alter_ticket_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
