# Generated by Django 5.0.7 on 2024-08-02 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0008_remove_ticket_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
