# Generated by Django 5.0.7 on 2024-10-17 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_projet', '0015_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='food',
        ),
    ]
